insert into public.cafe_status_reviews (
  status_source, cafe_source, cafe_source_id, country_code, city_key,
  cafe_name, cafe_address, google_place_id, google_business_status, google_maps_url,
  matched_name, matched_address, review_category, review_reason, status_checked_at, is_current
) values
  ('google_places', 'cafenomad', '100a5e2d-b287-4487-9a59-d2455c746f64', 'TW', 'yilan', '禾子咖啡', '宜蘭市農權路三段197巷1弄2號 Yilan City', 'ChIJNX6MOpTkZzQRTb3F-tQIGIs', 'CLOSED_TEMPORARILY', '', '禾子咖啡', '農權路三段197巷1弄2號', 'review', 'Google Places businessStatus = CLOSED_TEMPORARILY', now(), true),
  ('google_places', 'cafenomad', '13ede237-555c-4dbf-a793-c9be8beecb10', 'TW', 'yilan', 'GOROGORO', '宜蘭縣宜蘭市中山路二段187巷25號', 'ChIJV0iSx8LkZzQRqngIeXPP5jA', 'CLOSED_PERMANENTLY', '', 'GOROGORO', '中山路二段187巷25號', 'suspected_closed', 'Google Places businessStatus = CLOSED_PERMANENTLY', now(), true),
  ('google_places', 'cafenomad', '235065e9-d2a3-47fd-9df6-73487bad5271', 'TW', 'yilan', '語後咖啡 Ameagari Cafe', '宜蘭市延平路42巷6號', 'ChIJ7-LrbdjkZzQRM8U0tcF9Jso', 'CLOSED_TEMPORARILY', '', '語後咖啡', '延平路42巷6號', 'review', 'Google Places businessStatus = CLOSED_TEMPORARILY', now(), true),
  ('google_places', 'cafenomad', '23cb017d-6d35-4ca1-a11a-3adde3f00601', 'TW', 'yilan', '郁見幸福', '宜蘭市健康路二段117號', 'ChIJTefAM-jkZzQRiTwsG8AfGdI', 'CLOSED_TEMPORARILY', '', '郁見幸福Coffe&Cake', '健康路二段117號', 'review', 'Google Places businessStatus = CLOSED_TEMPORARILY', now(), true),
  ('google_places', 'cafenomad', '4d48c951-e7ec-4f79-8e7b-a9d213d1f2c9', 'TW', 'yilan', 'HaoHaoKaffe(行口文旅店)', '宜蘭縣宜蘭市康樂路14號', 'ChIJmTySTNrkZzQRWGY5Yyh2OL4', 'CLOSED_PERMANENTLY', '', 'HaoHaoKaffe 行口文旅店', '康樂路14號一樓', 'suspected_closed', 'Google Places businessStatus = CLOSED_PERMANENTLY', now(), true),
  ('google_places', 'cafenomad', '51ffe071-f7ce-46ec-8f70-bc4da90b6c65', 'TW', 'yilan', '合盛太平咖啡', '宜蘭縣宜蘭市中山路三段145號', 'ChIJ1dytifnlZzQRWFNgf9_Fxbs', 'CLOSED_PERMANENTLY', '', '飛魚食染-宜蘭店', '26044宜蘭縣宜蘭市中山路三段145號', 'suspected_closed', 'Google Places businessStatus = CLOSED_PERMANENTLY', now(), true),
  ('google_places', 'cafenomad', '6604d080-499c-41e9-b25e-16158ab3b212', 'TW', 'yilan', '老房子咖啡', '羅東鎮文化街53號', 'ChIJK4FSvXzmZzQR_KVd-MWjTiI', 'CLOSED_PERMANENTLY', '', '校長宿舍-老房子咖啡', '265宜蘭縣羅東鎮文化街53號', 'suspected_closed', 'Google Places businessStatus = CLOSED_PERMANENTLY', now(), true),
  ('google_places', 'cafenomad', '6c0f6d02-cedf-40a9-a619-dc4c830039a4', 'TW', 'yilan', '南澳好糧食堂 Good Eats Cafe', '蘇澳鎮南澳路13-1號', 'ChIJlZo2fSnbZzQRZh9BLYDWwDM', 'CLOSED_TEMPORARILY', '', '南澳好糧食堂', '蘇花路二段326巷18號', 'review', 'Google Places businessStatus = CLOSED_TEMPORARILY', now(), true),
  ('google_places', 'cafenomad', '74898d91-0dbd-4089-bfab-67510ac7f948', 'TW', 'yilan', '舒室咖啡', '宜蘭市慈安路61號', 'ChIJm2jgakrlZzQRmHnlV3KvS24', 'CLOSED_PERMANENTLY', '', '舒室', '260宜蘭縣宜蘭市慈安路61號', 'suspected_closed', 'Google Places businessStatus = CLOSED_PERMANENTLY', now(), true),
  ('google_places', 'cafenomad', '7509c810-3a15-4306-92ea-90dbe5dba74f', 'TW', 'yilan', 'ZeraCafe 頭城站舍', '宜蘭縣頭城鎮站舍巷1號', 'ChIJQ0VzMhr3ZzQRT5DrEv3mq2w', 'CLOSED_PERMANENTLY', '', '頭城站舍', '站舍巷1號', 'suspected_closed', 'Google Places businessStatus = CLOSED_PERMANENTLY', now(), true),
  ('google_places', 'cafenomad', '76f77c16-b544-4673-a9ce-21ed6f098ee7', 'TW', 'yilan', '九號咖啡音樂廣場', '宜蘭縣礁溪鄉溫泉路85號', 'ChIJC8xJOzb6ZzQRp4M6WdsOVbc', 'CLOSED_PERMANENTLY', '', '九號咖啡音樂廣場', '溫泉路1054號', 'suspected_closed', 'Google Places businessStatus = CLOSED_PERMANENTLY', now(), true),
  ('google_places', 'cafenomad', '904c5a82-d64a-4346-90f6-e7375b5dd1a9', 'TW', 'yilan', '破布烏咖啡 Popuwoo Cafe', '宜蘭縣三星鄉三星路六段465號', 'ChIJC-qYiy7gZzQRiap5iWm3MSg', 'CLOSED_TEMPORARILY', '', '破布烏咖啡 Popuwoo Cafe', '三星路六段465號', 'review', 'Google Places businessStatus = CLOSED_TEMPORARILY', now(), true),
  ('google_places', 'cafenomad', '94e6bbee-cec2-4727-a5a2-f9c8fa4079a9', 'TW', 'yilan', '光覺咖啡 Lighten Cafe', ' 宜蘭蘇澳鎮中原路228號', 'ChIJU3fgLU77ZzQRFnjQxR5vfr0', 'CLOSED_TEMPORARILY', '', '光覺咖啡 Lighten Cafe', '270宜蘭縣蘇澳鎮中原路228號', 'review', 'Google Places businessStatus = CLOSED_TEMPORARILY', now(), true),
  ('google_places', 'cafenomad', '99a7cfc5-f2ef-47ca-a374-d6752b8d3bb9', 'TW', 'yilan', 'PonPon 乓乓雜貨咖啡', '宜蘭縣礁溪鄉信義路71號', 'ChIJG4rDzEv6ZzQRr3zmZ4Ab6uQ', 'CLOSED_PERMANENTLY', '', 'PonPon 乓乓雜貨咖啡', '信義路71號', 'suspected_closed', 'Google Places businessStatus = CLOSED_PERMANENTLY', now(), true),
  ('google_places', 'cafenomad', 'bde1cb5b-8711-4f8d-ba73-48116757d42c', 'TW', 'yilan', '日吉咖啡gooddaycafe''', '宜蘭縣宜蘭市東港路59-11號', 'ChIJdcrfttnkZzQRRw79T8ufABU', 'CLOSED_PERMANENTLY', '', '日吉咖啡', '東港路二段431號', 'suspected_closed', 'Google Places businessStatus = CLOSED_PERMANENTLY', now(), true),
  ('google_places', 'cafenomad', 'd0f4ba73-c744-457c-b4cf-a8a1a0e29bff', 'TW', 'yilan', '大手小手咖啡屋', '260宜蘭縣宜蘭市建業路85號', 'ChIJtfn-2pPlZzQRcSKipgZ8-yY', 'CLOSED_TEMPORARILY', '', '大手小手咖啡屋', '建業路85號', 'review', 'Google Places businessStatus = CLOSED_TEMPORARILY', now(), true),
  ('google_places', 'cafenomad', 'd4cac5dc-768d-464e-a47d-f8694c399c9b', 'TW', 'yilan', 'Resort Brew Coffee Co.', '宜蘭市農權路二段30號', 'ChIJSW_7gunkZzQRuueWp018JQM', 'CLOSED_PERMANENTLY', '', 'resort.brew.coffee.co. 7/15最後營業', '農權路二段30號', 'suspected_closed', 'Google Places businessStatus = CLOSED_PERMANENTLY', now(), true),
  ('google_places', 'cafenomad', 'd83b252c-295c-441e-870f-1cd36c271189', 'TW', 'yilan', '歐麟咖啡館', '宜蘭市女中路二段389號1樓', 'ChIJNXjj6ujkZzQRw0Z2vg5aKVE', 'CLOSED_PERMANENTLY', '', '歐麟咖啡館', '女中路二段389號1 樓', 'suspected_closed', 'Google Places businessStatus = CLOSED_PERMANENTLY', now(), true),
  ('google_places', 'cafenomad', 'eea24637-a454-4067-9771-5393a93b0839', 'TW', 'yilan', 'Café SoDavid', '宜蘭縣羅東鎮中華路255號', 'ChIJb_IbDdTlZzQR-E2HSpo4Nw0', 'CLOSED_TEMPORARILY', '', 'CAFÉ SoDavid', '中華路255號26541 Lotung', 'review', 'Google Places businessStatus = CLOSED_TEMPORARILY', now(), true),
  ('google_places', 'cafenomad', 'eef9222f-0210-48c9-872d-46bd65828a79', 'TW', 'yilan', 'Link88', '宜蘭縣蘇澳鎮中山路一段88號', 'ChIJvwEsiDboZzQR8rqSG04FhIE', 'CLOSED_TEMPORARILY', '', 'Link88咖啡廳（寵物友善）', '中山路一段88號', 'review', 'Google Places businessStatus = CLOSED_TEMPORARILY', now(), true),
  ('google_places', 'cafenomad', 'fab4d0b8-114a-4459-b5cf-f415ab35a1bf', 'TW', 'yilan', '熊來了', '宜蘭縣宜蘭市民權路二段178號', 'ChIJC2aes-3kZzQR6V2mAxStjZc', 'CLOSED_PERMANENTLY', '', '熊與喵咖啡(永久歇業)｜活動需求請搜尋［好時光派對企劃］', '260宜蘭縣宜蘭市嵐峰路二段20號', 'suspected_closed', 'Google Places businessStatus = CLOSED_PERMANENTLY', now(), true)
on conflict (status_source, cafe_source, cafe_source_id) do update set
  country_code = excluded.country_code,
  city_key = excluded.city_key,
  cafe_name = excluded.cafe_name,
  cafe_address = excluded.cafe_address,
  google_place_id = excluded.google_place_id,
  google_business_status = excluded.google_business_status,
  google_maps_url = excluded.google_maps_url,
  matched_name = excluded.matched_name,
  matched_address = excluded.matched_address,
  review_category = excluded.review_category,
  review_reason = excluded.review_reason,
  status_checked_at = excluded.status_checked_at,
  is_current = excluded.is_current;
